// One-time helper: pull the exact React + ReactDOM production bundles out of the
// currently-deployed index.html so the build can re-embed the same versions
// without any network dependency.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const html = readFileSync("index.html", "utf8");

// The ReactDOM bundle contains a literal `<script>` inside a string, but its
// matching close is escaped as `\x3c/script>`, so it never produces a stray
// </script>. That makes a non-greedy <script>...</script> split safe here.
const blocks = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]);

if (blocks.length !== 3) {
  console.error(`Expected 3 <script> blocks, found ${blocks.length}. Aborting.`);
  process.exit(1);
}

const [react, reactDom, app] = blocks;

// Sanity: identify by their license banners.
if (!/react\.production\.min\.js/.test(react)) {
  console.error("Block 1 does not look like react.production.min.js"); process.exit(1);
}
if (!/react-dom\.production\.min\.js/.test(reactDom)) {
  console.error("Block 2 does not look like react-dom.production.min.js"); process.exit(1);
}
if (!/ReactDOM\.createRoot/.test(app)) {
  console.error("Block 3 does not look like the app bundle"); process.exit(1);
}

mkdirSync("vendor", { recursive: true });
writeFileSync("vendor/react.production.min.js", react, "utf8");
writeFileSync("vendor/react-dom.production.min.js", reactDom, "utf8");

console.log("Extracted vendor bundles:");
console.log(`  vendor/react.production.min.js      ${react.length} bytes`);
console.log(`  vendor/react-dom.production.min.js  ${reactDom.length} bytes`);
console.log(`  (app block was ${app.length} bytes — not saved, it is regenerated by the build)`);
